import os
from dotenv import load_dotenv
from anthropic import Anthropic 
import pandas
import argparse

load_dotenv()



client = Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))

def create_propt(text):
    """
    create input prompt for the language model.
    Args:
    prompt for test classification
    """
    instruction = 'Analyse each review and tell the underlying sentiment positive or negative?'
    formatting = '"Positive" or "Negative"'
    return f'Text: {text}\n{instruction}\nAnswer ({formatting})'

def classify(text):
    """Classify the input text
    Args:
        text: the text to classify.
    Returs:
    class label ("POSITIVE" OR "NEGATIVE")
    """
    
    prompt = create_propt(text)
    answer = call_ll(prompt)
    print(answer)

def call_ll(prompt):
    """Call LLM with input prompt and return answer
    Args
    prompt: prompt to send to the language model
    
    returns:
        Answer generated by LLM
    """
    try:
        response = client.messages.create(
            model='claude-3-5-haiku-latest',
            max_tokens=5,
            messages=[
                {
                    'role': 'user',
                    'content': prompt
                }
            ]
            
        )
        return response.content[0].text
    
    except Exception as e:
        print(f'An error occured: {e}')
        return None
    

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('path', type=str, help='A text to classify')
    args = parser.parse_args()
    df = pandas.read_csv(args.path)
    df['class'] = df.apply(classify)
    # print(df)
    
    
    
    
 
 
 
# Message(id='msg_01236peb2FBeBVVDDhvNfTJm', 
#         content=[TextBlock(citations=None, text='Negative', type='text')], 
#         model='claude-3-5-haiku-20241022', 
#         role='assistant', stop_reason='end_turn', 
#         stop_sequence=None, 
#         type='message', 
#         usage=Usage(cache_creation_input_tokens=0, cache_read_input_tokens=0, input_tokens=38, output_tokens=5))